apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-multisource1
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  sources:

  - repoURL: https://github.com/sanjay-1992/deploy-argocd-app.git
    targetRevision: main
    ref: values

  - repoURL: https://github.com/sanjay-1992/springboot-helm-chart.git
    targetRevision: main
    path: helm-charts/springboot
    helm:
      valueFiles:
        - $values/deploy/dev/values.yaml
    path: .
    helm:
      valueFiles:
        - $values/deploy/dev/values.yaml
